# Generated by Django 6.0.3 on 2026-05-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_pics/'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'restaurant')},
        ),
    ]
