# Generated by Django 6.0.3 on 2026-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunt', '0002_alter_review_image_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
    ]
