# Generated by Django 6.0.5 on 2026-05-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunt', '0005_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_student_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='student_promo_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
