# Generated by Django 6.0.5 on 2026-06-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunt', '0007_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closed_days',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='operating_days',
            field=models.TextField(blank=True, null=True),
        ),
    ]
