# Generated by Django 6.0.3 on 2026-06-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunt', '0008_alter_post_image'),
        ('foodhunt', '0008_restaurant_closed_days_restaurant_operating_days'),
    ]

    operations = [
    ]
