# Generated by Django 6.0.3 on 2026-06-04 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunt', '0009_merge_20260603_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RestaurantVote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodhunt.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodhunt.user')),
            ],
            options={
                'db_table': 'restaurant_vote',
                'managed': True,
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
