# Generated by Django 6.0.3 on 2026-06-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunt', '0010_restaurant_dislikes_count_restaurant_likes_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='likes_count',
        ),
    ]
