# Generated by Django 6.0.6 on 2026-07-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunt', '0012_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
